name: Get and Save Latest Release Binaries

on:
  push:
    branches:
      - main  # Change this to your default branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout get.voltmetrix.com code
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

      - name: Get latest release information
        id: get_release
        run: |
          release=$(curl -s https://api.github.com/repos/voltmetrixdotcom/cli/releases/latest | jq -r '.tag_name')
          echo "::set-output name=release::$release"

      - name: Download binaries
        run: |
          release="${{ steps.get_release.outputs.release }}"
          curl -L "https://github.com/voltmetrixdotcom/cli/releases/download/${release}/voltmetrix" -o "voltmetrix"
          curl -L "https://github.com/voltmetrixdotcom/cli/releases/download/${release}/voltmetrix.exe" -o "voltmetrix.exe"

      - name: Move binaries to existing folders
        run: |
          mv voltmetrix linux/
          mv voltmetrix.exe windows/

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git config --local user.email "ignacio@voltmetrix.com"
          git config --local user.name "xe-nvdk"
          git add .
          git commit -m "Update binaries to ${{ steps.get_release.outputs.release }}"
          git push
