name: Handle Build Artifacts

on:
  repository_dispatch:
    types: build-artifacts

jobs:
  handle-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: linux/voltmetrix # Path where artifacts will be saved in the target repository
